# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional

from .._models import BaseModel

__all__ = ["DevboxExecutionDetailView"]


class DevboxExecutionDetailView(BaseModel):
    devbox_id: Optional[str] = None
    """Devbox id where command was executed."""

    exit_status: Optional[int] = None
    """Exit status of command execution."""

    stderr: Optional[str] = None
    """Standard error generated by command."""

    stdout: Optional[str] = None
    """Standard out generated by command."""
